# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: redis://:action_cable@pub-redis-13860.us-east-1-1.1.ec2.garantiadata.com:13860

development:
  adapter: async

test:
  adapter: async
