# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c0a398477f0f9699fb63bf86b3fa4b1c3b246fb2c200b1f1198a47a8af59182d2abf5afa79da61825d3d0a366366c5c6f4c027d02140c99d22c29ae6deaee6a

test:
  secret_key_base: 475bdecbaafa08b260d3d2b7dd140b5fa83efdfb764899b92dbd1728c40f675812f80ba21cf4274b6b6b26de0d16b6b27e9fdb06b9feb0482b40ab6f10fdde97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
